---
name: Optimize Init

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'optimize-init'
      - 'optimize-init-*'

jobs:
  Compile:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          ref: dev
          repository: EA31337/EA31337-classes
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2361
          path: Stg_ElliottWave.mq4
          verbose: true
      - name: Copy Math includes
        run: Copy-Item -Recurse ../MetaTrader/MQL5/Include/Math Include/
      - name: Compile for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2515
          path: Stg_ElliottWave.mq5
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EA
          path: '*.ex?'
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sets
          path: 'sets/optimize/*.set'
  Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: optimize-som
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
