---
name: Backtest

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - 'master'
      - 'dev*'
    paths-ignore:
      - '*.md'
  push:
    branches:
      - 'master'
      - 'dev*'
    paths-ignore:
      - '*.md'

jobs:
  Compile:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          repository: EA31337/EA31337-classes
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          path: Stg_ElliottWave.mq4
          include: .
          mt-version: 5.0.0.2361
          verbose: true
      - name: Compile for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          path: Stg_ElliottWave.mq5
          include: .
          mt-version: 5.0.0.2515
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: '*.ex?'
  Test:
    needs: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        month: [1]
        year: [2018, 2019]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files
      - name: Run strategy
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "Stg_ElliottWave"
          BtMonths: ${{ matrix.month }}
          BtYears: ${{ matrix.year }}
