---
name: Backtest

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - 'master'
      - 'dev*'
    paths-ignore:
      - '*.md'
  push:
    branches:
      - 'master'
      - 'dev*'
    paths-ignore:
      - '*.md'

jobs:
  Compile:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          ref: dev
          repository: EA31337/EA31337-classes
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2361
          path: Stg_ElliottWave.mq4
          verbose: true
      - name: Copy Math includes
        run: Copy-Item -Recurse ../MetaTrader/MQL5/Include/Math Include/
      - name: Compile for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2515
          path: Stg_ElliottWave.mq5
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EA
          path: '*.ex?'
  Test:
    needs: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        month: [1]
        year: [2018, 2019]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: EA
      - name: Run strategy
        uses: ea31337/mql-tester-action@master
        with:
          BtDeposit: 100000
          BtDest: ${{ github.workspace }}/_results
          BtMonths: ${{ matrix.month }}
          BtYears: ${{ matrix.year }}
          OptFormatBrief: true
          OptFormatJson: true
          OptVerbose: true
          TestExpert: "Stg_ElliottWave"
          TestPeriod: M1
          TestReportName: Report-${{ matrix.year }}-${{ matrix.month }}
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ${{ github.workspace }}/_results/*.*
